server.port=9001

spring.datasource.url=jdbc:mysql://192.168.1.3:3306/job_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=bechir@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.rabbitmq.host=192.168.1.3
spring.rabbitmq.port=5672
spring.rabbitmq.username=bechir
spring.rabbitmq.password=bechir


welcome.message=Bienvenue sur le microservice Job!