spring.application.name=eureka
server.port=8761

# pour ne pas s'enregistrer dans le registry
eureka.client.register-with-eureka=false
#pour ne pas enregister le trafic des instances dans le bd
eureka.client.fetch-registry=false